const browserGlobals = {
  Array: "readonly",
  Boolean: "readonly",
  CSS: "readonly",
  Date: "readonly",
  Error: "readonly",
  IntersectionObserver: "readonly",
  JSON: "readonly",
  Map: "readonly",
  Math: "readonly",
  Number: "readonly",
  Object: "readonly",
  Promise: "readonly",
  RegExp: "readonly",
  Set: "readonly",
  String: "readonly",
  TypeError: "readonly",
  URL: "readonly",
  clearInterval: "readonly",
  clearTimeout: "readonly",
  decodeURIComponent: "readonly",
  document: "readonly",
  encodeURIComponent: "readonly",
  getComputedStyle: "readonly",
  isNaN: "readonly",
  localStorage: "readonly",
  matchMedia: "readonly",
  navigator: "readonly",
  parseInt: "readonly",
  setInterval: "readonly",
  setTimeout: "readonly",
  window: "readonly",
};

const nodeGlobals = {
  Array: "readonly",
  Boolean: "readonly",
  Buffer: "readonly",
  __dirname: "readonly",
  __filename: "readonly",
  clearTimeout: "readonly",
  console: "readonly",
  Date: "readonly",
  Error: "readonly",
  JSON: "readonly",
  Map: "readonly",
  Math: "readonly",
  Number: "readonly",
  Object: "readonly",
  Promise: "readonly",
  RegExp: "readonly",
  Set: "readonly",
  String: "readonly",
  TypeError: "readonly",
  URL: "readonly",
  module: "readonly",
  process: "readonly",
  require: "readonly",
  setTimeout: "readonly",
};

const commonRules = {
  curly: ["error", "all"],
  eqeqeq: ["error", "always"],
  "no-eval": "error",
  "no-implied-eval": "error",
  "no-new-func": "error",
  "no-undef": "error",
  "no-unused-vars": ["error", { args: "none", caughtErrors: "none" }],
  "no-var": "off",
  "prefer-const": "error",
};

export default [
  {
    ignores: [".pages-dist/**", "node_modules/**", "recipes/**/target/**"],
  },
  {
    files: ["assets/**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "script",
      globals: browserGlobals,
    },
    rules: commonRules,
  },
  {
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: nodeGlobals,
    },
    rules: commonRules,
  },
  {
    files: ["tests/**/*.cjs", "playwright.config.cjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: nodeGlobals,
    },
    rules: commonRules,
  },
  {
    files: ["tests/browser/**/*.cjs"],
    languageOptions: { globals: { document: "readonly" } },
  },
];
